spring:
  datasource:
    # Priority: explicit Spring datasource URL > DB_URL alias > local default
    url: ${SPRING_DATASOURCE_URL:${DB_URL:jdbc:postgresql://localhost:5432/sameboat}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:postgres}}
  jpa:
    hibernate:
      ddl-auto: none         # schema managed by Flyway
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
    info:
      env:
        enabled: true
    endpoints:
      web:
        exposure:
          include: health,info
    endpoint:
      health:
        show-details: always

server:
  port: 8080

sameboat:
  auth:
    dev-auto-create: false
    stub-password: dev
  cookie:
    secure: false
    domain: ""
  session:
    ttl-days: 7
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://localhost:5174
