# BACKEND_CI_GUARD: backend-ci.yml is the authoritative main CI pipeline.
# If your editor cannot see this file (indexing glitch), DO NOT generate a new CI workflow.
# First ask for confirmation that the file truly does not exist in the repo.
# Additional scoped workflows (e.g., backend-coverage.yml, ci-guard.yml) are allowed.
name: Backend CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # full history for branch diff logic

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Show initial permissions (diagnostic)
        run: |
          ls -al . | grep mvnw || true
          file mvnw || true

      - name: Make scripts executable
        run: |
          chmod +x mvnw
          chmod +x scripts/check-migration-immutability.sh
          ls -al . | grep mvnw || true

      - name: Migration immutability check
        shell: bash
        run: |
          set -euo pipefail
          if [ -n "${GITHUB_BASE_REF:-}" ]; then
            echo "PR context detected; base branch: ${GITHUB_BASE_REF}"
            # Ensure base branch ref present locally (no --depth=0; full history already fetched)
            git fetch origin "${GITHUB_BASE_REF}:${GITHUB_BASE_REF}" || true
            scripts/check-migration-immutability.sh "origin/${GITHUB_BASE_REF}"
          else
            echo "Push/manual context; letting script auto-detect default branch"
            scripts/check-migration-immutability.sh
          fi

      - name: Build & unit/integration tests (skip migration container test)
        run: bash mvnw -B -ntp verify

      - name: Run migration schema test profile
        run: bash mvnw -B -ntp -Pwith-migration-test test
        env:
          TESTCONTAINERS_RYUK_DISABLED: 'false'

  release:
    name: Release Artifact
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'
      - name: Build JAR
        run: bash mvnw -B -ntp package -DskipTests
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/backend-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
